### PR TITLE
v0.4

### PR DESCRIPTION
**Pull request by cfh294**
Includes:

- Update to python3
- New "-srid" parameter for script
- Additional documentation
- .gitignore file

### CODE REVIEW

**Comment by johnjreiser** [comment]
Failing for me on Python 3.8:

de_parcels -> https://firstmap.delaware.gov/arcgis/rest/services/PlanningCadastre/DE_State_Parcels/MapServer/0/query
tablen=pubdata.de_parcels_20190722
/storage/areaplot/repositories/test/chupaESRI/chupaESRI.py:296: SyntaxWarning: invalid escape sequence \w
  groups = re.match("https?://([\w\:\.\-]+)(/.*)", in_endpoint_url).groups()
2019-07-22 20:01:19,483 - ERROR - Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/storage/areaplot/repositories/test/chupaESRI/chupaESRI.py", line 477, in <module>
    main()
  File "/storage/areaplot/repositories/test/chupaESRI/chupaESRI.py", line 392, in wrap
    return f(ap.parse_args(), *args, **kwargs)
  File "/storage/areaplot/repositories/test/chupaESRI/chupaESRI.py", line 407, in main
    oids = _check_oid_range(domain, path)
  File "/storage/areaplot/repositories/test/chupaESRI/chupaESRI.py", line 354, in _check_oid_range
    response = requests.get(q_url).json()
  File "/home/jreiser/.local/lib/python3.8/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib64/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by johnjreiser** [comment]
Please check the commit on your fork and let me know if you'd like to make further changes. Running that now against the service referenced above. Will compare the two downloads to verify. Thank you for your contribution!

**Comment by johnjreiser** [comment]
No discernible differences between the two outputs. If you have no other changes to the commit I made on this PR, I'll merge. Thanks again!

**Comment by cfh294** [comment]
looks good to me. I wonder why it let the non-literal string go through in 3.6 (my local version).

**Pull request merged**
